# Generated by Django 5.2.8 on 2026-02-13 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Cairo', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(default='email@gmail.com', max_length=254, unique=True)),
                ('working_hours', models.CharField(max_length=100)),
                ('hospital_type', models.CharField(choices=[('حكومي', 'حكومي'), ('خاص', 'خاص')], default='حكومي', max_length=10)),
                ('password', models.CharField(default='enter your password', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('donor', 'Donor')], max_length=20)),
                ('status', models.CharField(choices=[('قيد الانتظار', 'قيد الانتظار'), ('موافق عليه', 'موافق عليه'), ('قيد المراجعة', 'قيد المراجعة'), ('مرفوض', 'مرفوض')], default='pending', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر '), ('انثي', 'انثي')], max_length=10)),
                ('medical_record_number', models.CharField(max_length=50)),
                ('HLA_A_1', models.CharField(blank=True, max_length=10, null=True)),
                ('HLA_A_2', models.CharField(blank=True, max_length=10, null=True)),
                ('HLA_B_1', models.CharField(blank=True, max_length=10, null=True)),
                ('HLA_B_2', models.CharField(blank=True, max_length=10, null=True)),
                ('HLA_DR_1', models.CharField(blank=True, max_length=10, null=True)),
                ('HLA_DR_2', models.CharField(blank=True, max_length=10, null=True)),
                ('PRA', models.FloatField(blank=True, null=True)),
                ('CMV_status', models.BooleanField(default=False)),
                ('EBV_status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('supervisor_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.TextField()),
                ('message', models.TextField(default='title')),
                ('alert_type', models.CharField(choices=[('معلومة', 'معلومة'), ('تحذير', 'تحذير'), ('طبي', 'طبي'), ('حرج', 'حرج')], max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_available', models.CharField(choices=[('كلية', 'كلية'), ('كبد', 'كبد'), ('قلب', 'قلب'), ('رئة', 'رئة'), ('بنكرياس', 'بنكرياس')], default='Kindy', max_length=20)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.hospital'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('مجدول', 'مجدول'), ('مكتمل', 'مكتمل'), ('ملغى', 'ملغى')], default='مجدول', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospital')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.TextField()),
                ('message', models.TextField(default='title')),
                ('alert_type', models.CharField(choices=[('معلومة', 'معلومة'), ('تحذير', 'تحذير'), ('حرج', 'حرج')], max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MRIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_scan', models.ImageField(blank=True, null=True, upload_to='mri/before/')),
                ('after_scan', models.ImageField(blank=True, null=True, upload_to='mri/after/')),
                ('ai_result', models.TextField(blank=True, null=True)),
                ('mismatch_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mri_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=50)),
                ('match_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('قيد الانتظار', 'قيد الانتظار'), ('مطابق', 'مطابق'), ('مرفوض', 'مرفوض')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_matches', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_percentage'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_needed', models.CharField(choices=[('كلية', 'كلية'), ('كبد', 'كبد'), ('قلب', 'قلب'), ('رئة', 'رئة'), ('بنكرياس', 'بنكرياس')], default='Kindy', max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('level', models.CharField(choices=[('اولوليه عاليه', 'اولوليه عاليه'), ('اولوليه متوسطة', 'اولوليه متوسطة'), ('اولوليه منخفضه', 'اولوليه منخفضه')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_number', models.CharField(max_length=50, unique=True)),
                ('surgery_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('قلب', 'قلب'), ('كبد', 'كبد'), ('كلى', 'كلى'), ('رئة', 'رئة'), ('عظام', 'عظام')], default='كلى', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('مجدولة', 'مجدولة'), ('جاريه', 'جاريه'), ('مكتملة', 'مكتملة'), ('تحت المتابعة', 'تحت المتابعة')], default='مجدولة', max_length=20)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('operation_room', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('organ_matching', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organmatching')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_summary', models.TextField()),
                ('complications', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='surgery_reports/files/')),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='surgery_reports/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.surgery')),
            ],
        ),
        migrations.CreateModel(
            name='UserChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('منخفض', 'منخفض'), ('متوسط', 'متوسط'), ('عالي', 'عالي')], max_length=20)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chronicdisease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='user_reports/')),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('مكتمل', 'مكتمل'), ('تحت المراجعه', 'تحت المراجعه')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
