# Generated by Django 5.2.8 on 2026-05-20 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('تحت المراجعه', 'تحت المراجعه'), ('نشط', 'نشط'), ('مرفوض', 'مرفوض')], default='تحت المراجعه', max_length=20),
        ),
        migrations.AddField(
            model_name='organmatching',
            name='request_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='القاهرة', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='report_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_available',
            field=models.CharField(choices=[('كلية يمنى', 'كلية يمنى'), ('كلية يسرى', 'كلية يسرى'), ('كبد', 'كبد')], default='كبد', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='القاهره', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='organ_type',
            field=models.CharField(choices=[('كلية يمنى', 'كلية يمنى'), ('كلية يسرى', 'كلية يسرى'), ('كبد', 'كبد')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='status',
            field=models.CharField(choices=[('قيد التحليل', 'قيد التحليل'), ('تحت المراجعه', 'تحت المراجعه'), ('تحت المطابقه', 'تحت المطابقه'), ('قيد الانتظار', 'قيد الانتظار')], default='قيد التحليل', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmedicalprofile',
            name='organ_needed',
            field=models.CharField(choices=[('كلية يمنى', 'كلية يمنى'), ('كلية يسرى', 'كلية يسرى'), ('كبد', 'كبد')], default='كبد', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientpriority',
            name='level',
            field=models.CharField(choices=[('اولوليه عاليه', 'اولوليه عاليه'), ('اولوليه متوسطة', 'اولوليه متوسطة'), ('اولوليه منخفضه', 'اولوليه منخفضه'), ('حرجة جداً', 'حرجة جداً')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='department',
            field=models.CharField(choices=[('كبد', 'كبد'), ('كلى', 'كلى')], default='كلى', max_length=50),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('مجدولة', 'مجدولة'), ('جاريه', 'جاريه'), ('تمت بنجاح', 'تمت بنجاح'), ('فشلت', 'فشلت'), ('تحت المتابعة', 'تحت المتابعة')], default='مجدولة', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'patient'), ('donor', 'donor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('قيد الانتظار', 'قيد الانتظار'), ('جاهز', 'جاهز'), ('قيد المراجعة', 'قيد المراجعة'), ('تحت المطابقه', 'تحت المطابقه'), ('تحت العمليه', 'تحت العمليه'), ('مرفوض', 'مرفوض')], default='قيد الانتظار', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='report_type',
            field=models.CharField(choices=[('اشعه', 'اشعه'), ('تحاليل', 'تحاليل'), ('تقرير طبي', 'تقرير طبي')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='state',
            field=models.CharField(choices=[('مكتمل', 'مكتمل'), ('تحت الاجراء', 'تحت الاجراء')], max_length=20),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('منخفض', 'منخفض'), ('متوسط', 'متوسط'), ('عالي', 'عالي'), ('حرج', 'حرج')], default='منخفض', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency_per_day', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='core.ministry'),
        ),
        migrations.CreateModel(
            name='MinistryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.TextField()),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('خطر', 'خطر'), ('تحذير', 'تحذير'), ('تم الحل', 'تم الحل'), ('حرج', 'حرج')], max_length=20)),
                ('ALERT_Status', models.CharField(choices=[('متابعة التحقيق', 'متابعة التحقيق'), ('قيد التحقيق', 'قيد التحقيق')], max_length=20)),
                ('priority', models.CharField(choices=[('منخفضة', 'منخفضة'), ('متوسطة', 'متوسطة'), ('عالية', 'عالية')], default='متوسطة', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.ministry')),
                ('sender_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_notifications', to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
                ('ministry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ministry')),
            ],
        ),
    ]
